/*
 * generated by Xtext 2.20.0
 */
package de.htwdd.expressEMF


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ExpressStandaloneSetup extends de.htwdd.expressEMF.ExpressStandaloneSetupGenerated {

	def static void doSetup() {
		new ExpressStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
