/*
 * generated by Xtext 2.20.0
 */
package de.htwdd.expressEMF.step.ide;


/**
 * Use this class to register ide components.
 */
public class StepIdeModule extends AbstractStepIdeModule {
}
