/*
 * generated by Xtext 2.20.0
 */
package de.htwdd.expressEMF.step;

import com.google.inject.Injector;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class StepStandaloneSetup extends StepStandaloneSetupGenerated {

	public static void doSetup() {
		new StepStandaloneSetup().createInjectorAndDoEMFRegistration();
	}

	@Override
	public Injector createInjectorAndDoEMFRegistration() {
		EcoreStandaloneSetup.doSetup();
		return super.createInjectorAndDoEMFRegistration();
	}

	
}
