/*
 * generated by Xtext 2.20.0
 */
package de.htwdd.expressEMF.step.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class StepUiModule extends AbstractStepUiModule {

	public StepUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
