/*
 * generated by Xtext 2.20.0
 */
package de.htwdd.expressEMF;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class StepStandaloneSetup extends StepStandaloneSetupGenerated {

	public static void doSetup() {
		new StepStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
